services:
  vault:
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_SKIP_MLOCK: "true"
      SKIP_SETCAP: "true"
  vault-init:
    cap_add:
      - IPC_LOCK
  composer:
    environment:
      VAULT_TOKEN: "token-composer"
  object-storage:
    environment:
      VAULT_TOKEN: "token-object-storage"
  video-editor:
    environment:
      VAULT_TOKEN: "token-video-editor"
  notifications:
    environment:
      VAULT_TOKEN: "token-notifications"
