apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: tenant-grupo8-egs-deti-ua-pt
  labels:
    app: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_COMPOSER_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_COMPOSER_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_COMPOSER_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: dbport
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tenant-grupo8-egs-deti-ua-pt
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kc-db
  namespace: tenant-grupo8-egs-deti-ua-pt
  labels:
    app: kc-db
spec:
  serviceName: kc-db
  replicas: 1
  selector:
    matchLabels:
      app: kc-db
  template:
    metadata:
      labels:
        app: kc-db
    spec:
      containers:
        - name: kc-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_KEYCLOAK_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_KEYCLOAK_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uastream-secrets
                  key: POSTGRES_KEYCLOAK_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: dbport
          volumeMounts:
            - name: kc-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: kc-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kc-db
  namespace: tenant-grupo8-egs-deti-ua-pt
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: kc-db
