apiVersion: v1
kind: Secret
metadata:
  name: uastream-secrets
  namespace: tenant-grupo8-egs-deti-ua-pt
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  POSTGRES_COMPOSER_USER: "composer"
  POSTGRES_COMPOSER_PASSWORD: "composer"
  POSTGRES_COMPOSER_DB: "composer"
  POSTGRES_COMPOSER_DATABASE_URL: "postgresql://composer:composer@db:5432/composer"
  POSTGRES_KEYCLOAK_USER: "keycloak"
  POSTGRES_KEYCLOAK_PASSWORD: "keycloak"
  POSTGRES_KEYCLOAK_DB: "keycloak"
  KEYCLOAK_CLIENT_SECRET: "change-me-in-production"
  OBJECT_STORAGE_API_KEY: "stub-api-key"
  VIDEO_EDITOR_API_KEY: "stub-api-key"
  NOTIFICATIONS_API_KEY: "stub-api-key"
  VAULT_TOKEN: "token-composer"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-gmail-app-password"
  SMTP_FROM: "your-email@gmail.com"
  GRAFANA_ADMIN_PASSWORD: "admin"

