apiVersion: v1
kind: Secret
metadata:
  name: uastream-secrets
  namespace: tenant-grupo8-egs-deti-ua-pt
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  POSTGRES_KEYCLOAK_PASSWORD: "keycloak"
  KEYCLOAK_CLIENT_SECRET: "change-me-in-production"
  OBJECT_STORAGE_API_KEY: "stub-api-key"
  VIDEO_EDITOR_API_KEY: "stub-api-key"
  NOTIFICATIONS_API_KEY: "stub-api-key"
  VAULT_TOKEN: "token-composer"
